# Generated by Django 4.2.6 on 2023-11-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rurlapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='url_originale',
        ),
        migrations.RemoveField(
            model_name='url',
            name='url_raccourcie',
        ),
        migrations.AddField(
            model_name='url',
            name='lien',
            field=models.CharField(default=10, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.CharField(max_length=10),
        ),
    ]
