# Generated by Django 4.2.6 on 2024-01-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rurlapp', '0005_url_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='url_history',
        ),
    ]
